"""
TestWordGen tests the 'worktoy.examples.lorem_ipsum.WordGen' class.
"""
#  AGPL-3.0 license
#  Copyright (c) 2026 Asger Jon Vistisen
from __future__ import annotations

from typing import TYPE_CHECKING

from worktoy.examples.statistics import chiSquareTest
from . import ExampleTest
from worktoy.examples.lorem_ipsum import WordGen

if TYPE_CHECKING:  # pragma: no cover
  from typing import Any, Iterator, Type, TypeAlias, Union, Optional


class TestWordGen(ExampleTest):
  """
  TestWordGen tests the 'worktoy.examples.lorem_ipsum.WordGen' class.
  """

  def test_constructor(self) -> None:
    """
    Test the constructor of the WordGen class.
    """
    wordGen = WordGen()
    self.assertIsInstance(wordGen, WordGen)

  def test_word_gen(self) -> None:
    """
    Test the word generation functionality of the WordGen class.
    """
    wordGen = WordGen()
    word = wordGen.chooseWord()
    self.assertIsInstance(word, str)
    c = wordGen.minChars
    while c <= wordGen.maxChars:
      word = wordGen.chooseWord(c)
      self.assertIsInstance(word, str)
      self.assertGreaterEqual(len(word), c)
      c += 1

  def test_weights(self, ) -> None:
    """
    Tests that the words generated by 'WordGen' distribute reasonably
    according to the specified weights.
    """
    commons, uncommons, rares, words = [], [], [], []
    buckets = dict(common=commons, uncommon=uncommons, rare=rares)
    wordGen = WordGen()
    while len(words) < 1000:
      word = wordGen.chooseWord()
      words.append(word)
      name = wordGen.wordGroupName(word)
      list.append(buckets[name], word)
    expectedCommonWeight = 0.6
    expectedUncommonWeight = 0.3
    expectedRareWeight = 0.1
    actualCommonWeight = len(commons) / len(words)
    actualUncommonWeight = len(uncommons) / len(words)
    actualRareWeight = len(rares) / len(words)
    expected = (
      expectedCommonWeight,
      expectedUncommonWeight,
      expectedRareWeight,
      )
    actual = (
      actualCommonWeight,
      actualUncommonWeight,
      actualRareWeight,
      )
    chi2 = chiSquareTest(expected, actual)
