"""
TestDelta tests the 'delta' functions generated by the 'forwardDifference'
function in the 'worktoy.examples.mathematics' package.
"""
#  AGPL-3.0 license
#  Copyright (c) 2026 Asger Jon Vistisen
from __future__ import annotations

from typing import TYPE_CHECKING

from worktoy.examples.mathematics import forwardDifference
from worktoy.utilities import ExceptionInfo
from worktoy.waitaminute.mathematics import DomainError

from . import MathTest

if TYPE_CHECKING:  # pragma: no cover
  from typing import Any, TypeAlias, Type, Union


class TestDelta(MathTest):

  def test_delta(self, ) -> None:
    """Tests the 'delta' functions generated by the 'forwardDifference'
    function."""

    def a(n) -> float:
      return (1, 0, -1, 0)[n % 4]

    delta = forwardDifference(a, )

    with self.assertRaises(DomainError) as context:
      _ = delta(-69, 420)
    e = context.exception
    self.assertEqual(e.value, -69)
    self.assertEqual(e.minValue, 0)
    self.assertEqual(e.maxValue, float('inf'))
